### PR TITLE
Reminder emails, one-off availabilities, date/time formatting, additional backend options, and other small improvements

### PR DESCRIPTION
**Pull request by bikemike**
Hi Alex,

I have added what I feel are some useful features to my fork of easyappointments. Please have a look through my changes and consider adding these into your repository.

I've made a few changes to the database structure but have included migration scripts to accommodate this.

I have a few more features that I'd like to implement.
- add a notes screen where provider can enter appointment notes, and a screen to show the notes for a customer 
- email notification/reminder templates

Mike

### CODE REVIEW

**Comment by alextselegidis** [comment]
Hi Mike! Thank you! 

I will have to review the code before I pull it and this will take some time because I want to start the WordPress plugin for E!A. 

Just wanted to tell you that there is already the possibility to add appointment notes and view the customers appointments.

**Comment by alextselegidis** [comment]
Sorry for replying late - your pull request will be merged once the Easy!Appointments WordPress plugin is ready.

**Comment by bikemike** [comment]
are you still planning to merge any of these changes in?

**Comment by alextselegidis** [comment]
Yeah I want to do it sometime just before the release. I am not sure If I can automatically merge the code or do it manually but there are some improvements that I really like ;)

**Comment by bikemike** [comment]
Alex, do you still want to integrate these changes?

**Comment by alextselegidis** [comment]
Yeah sure, I know that a lot of time has passed since your pull request but I have seen your changes and they are great. The only thing is that I will do the merge manually because I do not want to include every one of them. So I will close the pull request and I will merge them from my local clone. 

Thanks again for your patience :+1:

**Pull request closed without merging**
