### PR TITLE
Configuration improvements

### PR DESCRIPTION
**Pull request by bukowskiadam**
I had to configure my installation to use SMTP server, so I've made some improvements about that, but also to persist my language setting upon update, beacause I've missed this feature.
You can safely ignore my pull request  - I won't bother with that :wink:

Anyway thanks for the great piece of software!

### CODE REVIEW

**Comment by icecoldfire** [comment]
Didn't see your pull request maybe you can add documentation for the possible languages like:


```
// options: 'english','german','greek','hungarian','portuguese',
// 'chinese','dutch','french','japanese','polish','spanish','italian',
// 'danish','luxembourgish','slovak','finnish','russian','romanian',
// 'turkish','hindi'

```

**Comment by bukowskiadam** [comment]
I was thinking about
```
// for the list of available languages please refer to application/config/config.php
```
but direct list looks better.

**Comment by alextselegidis** [comment]
Hi, to be honest I didn't test the app with SMTP until know. I will check your changes sometime today.

**Comment by alextselegidis** [comment]
First of all I would like to thank you for your pull request. I've read the changes you made and I see your point. But, I decided that I do not want to change the SMTP thing right now because the v1.1 is really close to release and no big changes should be made prior to that. 

In extend I think that I will remove PHPmailer from the project and will use the default mailing library of CodeIgniter which can be configured easier than the PHPmailer (at least inside the CodeIgniter application). It also has all the functionality I need anyway.

About the language configuration setting I will merge the other pull request which implemented only that. 

Have a nice day :)

**Comment by bukowskiadam** [comment]
As I've stated - I've made those changes for my needs. Switch to codeigniter's mailer and allow to set options will be great.
Anyway, thanks for the great piece of software.

**Comment by alextselegidis** [comment]
You are welcome :) 

I hope it serves your purposes well

**Pull request closed without merging**
