### PR TITLE
Payment integration via Stripe

### PR DESCRIPTION
**Pull request by casswarry0**
My implementation is according to https://stripe.com/docs/payments/accept-a-payment
Don't forget to: composer require stripe/stripe-php

[easyappointments.zip](https://github.com/alextselegidis/easyappointments/files/3848498/easyappointments.zip)

### CODE REVIEW

**Comment by kaustubhk24** [comment]
@casswarry0   Can you please give some details. How the stripe works with it?

**Comment by casswarry0** [comment]
@kaustubhk24 The easyappointments.zip attached to the pull request contains all changed files. Additionally you have to do "composer require stripe/stripe-php" to include the Stripe API into the project. The file "config-sample.php" contains the new constants required for the Stripe integration. I hope this answers all your questions.

**Comment by kaustubhk24** [comment]
@casswarry0  Thank you for your reply. I will check that.

**Comment by kaustubhk24** [comment]
@casswarry0  I added files. But doesn't asks for any payments. directly books appointments

**Comment by casswarry0** [comment]
@kaustubhk24 I assume you have a running instance of EasyAppointments and replaced the files with the files from the easyappointments.zip? Have you set "STRIPE_FEATURE = TRUE;" and also filled the 3 other STRIPE_ constants with values from your Stripe account (or with the generic test tokens) in the config.php? Have you created a task with a price set > 0 in  EasyAppointments admin interface?

**Comment by kaustubhk24** [comment]
@casswarry0  I will do that

**Comment by asyncopation** [comment]
Hi @casswarry0 @alextselegidis quick questions:

1. This implementation was attached as a ZIP file instead of merged in the PR.  Are there any plans to merge this implementation?
2. Since this modifies code outside of `src/vendor/stripe`, what is your approach in keeping this up to date with the latest features and fixes from `master`, security updates, etc.

Appreciate any insight, thanks!

**Comment by casswarry0** [comment]
Hi @asyncopation, I believe that the code was merged.

**Comment by alextselegidis** [comment]
Hello @casswarry0, 

Thanks for the PR, I will review and let you know of my findings. 

@asyncopation If merged then it will be done properly with composer.json updates etc. 

Also just to make clear, before a new feature is merged I always make sure it it well tested and can be easily used by anyone, technical or non technical individuals.

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Pull request merged**
