### PR TITLE
Added proper Docker support

### PR DESCRIPTION
**Pull request by flavienbwk**
The current docker configuration under the `./docker` directory does not work and is not optimal for quick testing & build.

- Added proper Docker configuration
- Added docker-compose support
- Added appropriate documentation
- Updated Docker configuration location to be at the root of the project (it's a bad practice to put it somewhere else as you're sure it won't integrate well with software over time).

### CODE REVIEW

**Comment by alextselegidis** [comment]
Hello! 

Thanks for your PR! 

The docker support was already updated on `develop` branch and will be merged to `master` once 1.5 hits the stable milestone. 

Could you please check that one first and let me know if there are any problems? 

Thanks!

<small>
<table>
<tr>
<td></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello! 

Any updates on this? 

<small>
<table>
<tr>
<td></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by flavienbwk** [comment]
Hi, I didn't know 1.5 was in prep. I won't invest more time on this sorry. 

My contribution can, however, be re-invested into the develop branch as it looks like it's having some issues similar to those addressed in this MR (mostly about non-optimized Docker images).

**Comment by fliot** [comment]
This PR is not only perfectly working with the full base, but it's also a must.
👍

**Comment by flavienbwk** [comment]
Thank you @fliot!

**Comment by alextselegidis** [comment]
Hello! 

Thanks again for submitting this PR! It is great to have input from experienced dev people out there. 

It was a bit unfortunate that the develop branch had already received an updated docker structure, that covers all of your points, plus the addition of phpMyAdmin and Mailhog into the development set up. 

Moreover I'm about to publish an official production E!A image, so that users can easily run E!A on any server without problems. 

Stay tuned for more updates!

<small>
<table>
<tr>
<td></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Pull request closed without merging**
