### PR TITLE
Add docker and docker-compose configuration.

### PR DESCRIPTION
**Pull request by rankun203**
Added [Dockerfile](https://docs.docker.com/engine/reference/builder/) for docker configuration and [docker-compose.yml](https://docs.docker.com/compose/) file for Docker Compose configuration.

### CODE REVIEW

**Comment by alextselegidis** [comment]
Hi! I run "docker-compose up" and head to http://localhost:8001 and I don't see anything. My host machine is running Windows. Am I missing something? 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by rankun203** [comment]
I'll test this out within a few days.

**Comment by alextselegidis** [comment]
Thanks!

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by rankun203** [comment]
Ah, I forgot to mention that you will need to copy the config-sample.php to config.php and change it accordingly. Once you've done that, the website will be up and running.

**Comment by alextselegidis** [comment]
@rankun203 Ok I'll try this again and get back to you. 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
I was able to start the containers but E!A cannot connect into the database. Could you please provide me a sample config.php file for reference? 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by rankun203** [comment]
@alexandrurapanu Take a look at `src/config-sample.php` of this PR, the sample is included.

**Comment by alextselegidis** [comment]
Merged in develop branch, thanks! 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Pull request closed without merging**
