### PR TITLE
Improved Docker support 

### PR DESCRIPTION
**Pull request by Valian**
In this pull request I've prepared a better Docker support, including development and production 
deployment configurations. I had to deploy this application, Docker is my favorite tool and PHP is not :wink:  I think it may be useful to others. Previous `Dockerfile` and `docker-compose.yml` were... just bad.  

Also I added a few lines to README, explaining how to run application as a container.

Tell me if I can improve anything.

### CODE REVIEW

**Comment by alextselegidis** [comment]
Hi Valian, there's already a docker configuration in the develop branch. 

Have you tried it yet? 

I would like to know the advantages of your configuration over it :) 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Valian** [comment]
Old configuration was using [deprecated links API]](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/), only suitable for development - no proper Docker Image was prepared in a build process. Basically, it was only creating environment for running PHP and files were mounted from the host. For production usage, it's a useless solution. 

I'm quite experienced in Docker, I even created few blog posts about best practices. What I prepared here is a really solid foundation to run EasyAppointments as a Docker container in production.

**Comment by MAfni** [comment]
OK

**Comment by alextselegidis** [comment]
Sounds great! I'll give it a try and merge it as soon as possible. 

Thanks for the merge request! 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hi there, 

I tried to start the docker containers with `docker-compose up` and I'm getting the following error: 

```
Building application
Step 1 : FROM wichon/alpine-apache-php
latest: Pulling from wichon/alpine-apache-php

[0Beaf3eaaf: Pulling fs layer
[0Bb1d1339a: Pulling fs layer
[0B32daeb9f: Pulling fs layer
Digest: sha256:6e8f00fb52811a3c70e5c99a6956789412326d35fcac2601def4910a0e8a35b8   430 B/430 B MBB
Status: Downloaded newer image for wichon/alpine-apache-php:latest
 ---> 2237f6edd8b9
Step 2 : ENV PROJECT_DIR /app APP_URL localhost
 ---> Running in 114dca29c7ba
 ---> 0d1a6e6d7146
Removing intermediate container 114dca29c7ba
Step 3 : RUN apk --no-cache add php-zlib php-mysqli php-gettext
 ---> Running in 641065ead320
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  php-gettext (missing):
    required by: world[php-gettext]
  php-mysqli (missing):
    required by: world[php-mysqli]
  php-zlib (missing):
    required by: world[php-zlib]
[31mERROR[0m: Service 'application' failed to build: The command '/bin/sh -c apk --no-cache add php-zlib php-mysqli php-gettext' returned a non-zero code: 3
```

I'm running this on a Windows machine with Docker v1.12.3 and Docker Compose 1.8.1. 

As it seems there are some PHP packages missing from the alpine linux distro. Any ideas on how we can correct this? 

Thanks :) 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Valian** [comment]
Ouch, looks like they moved PHP libraries out of official alpine package manager. I'll fix it later this week.

**Comment by alextselegidis** [comment]
Great, thanks!

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
@Valian Hey, did you had the chance to take a look in the docker configuration? 

Thanks :)

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Valian** [comment]
Working on it!

**Comment by alextselegidis** [comment]
@Valian Awesome, thanks 👍 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Valian** [comment]
@alextselegidis Take a look now, it should be working fine. Also improved `README.md` a bit.

**Comment by jamrizzi** [comment]
Could we use the Dockerfile I built? The existing Docker container is much bigger and does not support adding settings via environment variables.

https://github.com/jamrizzi/easyappointments-docker
https://hub.docker.com/r/jamrizzi/easyappointments/tags/

**Comment by alextselegidis** [comment]
Hey, thanks for your message. I'm currently validating all the available docker setups and I will end up integrating one the one that fits the best for development. 

I'm pretty sure that all of your great configurations would fit for the project but in the end we'll just have to pick one :)

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jamrizzi** [comment]
By the way, @Valian, if you have any pointer for my docker container, please mention them. I would suggest you make your docker container with Alpine so space isn't wasted and somehow find a way to pass in environment variables. The best Docker configuration might be a combination of ours.

**Comment by Valian** [comment]
@jamrizzi thanks for feedback!

In my previous version I was using alpine as a base image, but they moved most of the php packages out of apk repositories, that's why I've switched to `php-apache` (there's no `php-apache-alpine` version, but probably I could make it on my own). Anyway, base image size difference matters just for the first time, later it will be cached. 

About passing environment variables - it's of course possible, take a look at Readme file and [this](https://github.com/Valian/easyappointments/blob/2d3e03f54c086041fa64d76980fd446e45b8febf/docker-entrypoint.sh) entrypoint. You just define them either via `.env` file or directly in `docker run` command. Not all configuration variables are actually available to change through ENV, just ones related to database, smtp and host settings. I could update that to also include google key and similar. 

One big advantage I see with my solution over yours - it's ready for both development and production, with really easy docker-compose driven setup. You provided a very good Dockerfile, but inside you just download latest release, unzip it and use. There's no option to work with the code. In my solution, it's possible to mount code as a volume (automatically done when you run `docker-compose up`) or rebuild production image and check if everything is fine. Also, you can start entire application with one command, including database. I'm using that in other projects and it's working very well. 

@alextselegidis Try to work a bit with those two configurations and select one. It's your project, so your decision :P Of course, we could work together with @jamrizzi  to create something better.

**Comment by jamrizzi** [comment]
@Valian all docker containers work with docker compose. Also, I rarely find docker containers that let you manipulate the internal code. That's not the purpose for Docker containers. If someone wants to change the code inside the Docker container, they're supposed to make their own container. That's the way Docker's designed to be used.

**Comment by Valian** [comment]
@jamrizzi Yes, all containers work with docker-compose, but your repository don't have it. I've provided working docker-compose configs in this pull request, one for development and one for production. 

About manipulating code inside a container - on production, it's a very bad practice. But in development it's super-useful, you can start developing application with one command. In that case container is only an environment for running source code. I'm working with different languages in many projects, and ability to start development with the same command, no matter what technology, is great. 

Using Docker in development makes migration to other machine very easy, and gives you confidence that production container will also work (it's the same Dockerfile, just source code is mounted). What's the point of installing all dependencies on your host machine, if you already have everything prepared inside Docker? :wink: What's more, it's easier for new contributors to get involved into project.

**Comment by jamrizzi** [comment]
I agree development in a Docker container is super useful. I don't think that should be the container released for people to use in production though.  I'll go ahead and create a docker-compose.yml.

**Comment by jamrizzi** [comment]
I added a docker compose file
https://github.com/jamrizzi/easyappointments-docker/blob/master/docker-compose.yml

**Comment by Valian** [comment]
@alextselegidis Any updates on this?

**Comment by alextselegidis** [comment]
First of all I would like to thank both of you for your contribution to the project and for taking time to create these awesome Docker configurations. I really appreciate it 👍 👍 👍 

I've tested all available docker setups out there I found that  @Valian  fits the most to the project, so I'll merge that one. Being said I do not think that the other configurations will not work and I'm pretty sure that many users out there may find them great so I will provide external links for your repositories as well ( @jamrizzi @circa10a). 

As I'm not a Docker guru myself any suggestions for improvements are always welcome and will be taken into serious consideration. 

Cheers!

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by jamrizzi** [comment]
Ok, thank you

**Pull request merged**
