### PR TITLE
Add httponly flag to cookies

### PR DESCRIPTION
**Pull request by mtavkhelidze**
http://en.wikipedia.org/wiki/HTTP_cookie

### CODE REVIEW

**Comment by alextselegidis** [comment]
Hello, thanks for the pull request but I saw that you have edited some core CodeIgniter files and this is not the correct way to enable http cookies. 

I would like to have control on exact sections that require cookies and I can do this with the following library. 

https://ellislab.com/codeigniter/user-guide/helpers/cookie_helper.html

So the question is which part of the app would like to have cookies and what for?

**Comment by mtavkhelidze** [comment]
Hi Alex,

It's not an issue of enabling or disabling anything. Through CodeIgnater or
otherwise your application uses them.

What I did is I added last argument (true) to PHP core setcookie function
which sets HttpOnly flag (
http://en.wikipedia.org/wiki/HTTP_cookie#HttpOnly_cookie). That's a
security measure I needed, so I thought it might be useful for others too.

If CodeIgniter doesn't set this flag (and it appears that it doesn't), it
really should.

Misha


--
misha.tavkhelidze@gmail.com | +995 599 000 313 |
http://about.me/misha.tavkhelidze

What I cannot create I do not understand. — Richard Feynman


2015-06-07 20:57 GMT+04:00 Alex Tselegidis <notifications@github.com>:

**Comment by alextselegidis** [comment]
This is really interesting ... I will further investigate how CI treats the cookies and I will get back to you. 

Thanks!

**Comment by mtavkhelidze** [comment]
No problems.  Let me know if I can be of any help.

**Comment by alextselegidis** [comment]
Seems to me that you are right. I will merge your pull request. Many Thanks.

**Comment by mtavkhelidze** [comment]
Great!

**Pull request merged**
