### PR TITLE
Fix MySQL/MariaDB 5.5.x  backward compatibility issue with 'ea_consents' table (#518)

### PR DESCRIPTION
**Pull request by oxteam**
This change allows the creation and migration scripts to run on MySQL/MariaDB 5.5.x versions.

As explained in Ticket #518, old versions of MySQL/MariaDB do not support the way the `created`and `modified` field are declared. Because these old versions are still the default package used on long term support Linux distros (RHEL/CentOS), it is interesting to still be compatible with these DB engine versions.

The fix consists in:
- Using a `TIMESTAMP` type for the fields;
- Creating first the `modified` field to have it auto-updated according to the current timestamp;
- Setting the `created` field value in the 'Consents' model.

### CODE REVIEW

**Comment by alextselegidis** [comment]
You are right, at the beginning I was intended to only use this structure but it seems that there are more users that still have the 5.5 version so it makes sense to keep the app compatible. 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello @oxteam, after doing some research and having second thoughts I will keep the structure of the database the way it currently is. 

The thing is that MySQL 5.5 is not supported anymore and therefore users have to migrate sooner or later. Therefore it makes sense to use more modern schema and get the most out of the database. 

Thanks for the pull request anyway, with the release of 1.3.2 I'll update the system requirements in the documentation. 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Hello @oxteam again, from times to times I'm getting some reports from people failing to install the app due to their older MySQL version. Unfortunately many hosting environments haven't updated yet and therefore I'll have the pleasure to work with your pull request. Thanks again!

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by oxteam** [comment]
Hi Alex,

Happy to see that the fix can be useful.

Cheers

**Pull request merged**
