### PR TITLE
Extra working days outside the default working plan

### PR DESCRIPTION
**Pull request by Caine85**
Related to request #229 

I added the possibility to add an extra working days outside the default working plan.

There are two way to add am extra working day:
1) From a new button on top right of the backend calendar
2) From Users tab in backend, selecting Providers -> _choose a provider_ -> Working plan

In backend calendar, in 'agendaDay' view or in 'agendaWeek' view if by default a day is closed but it's added an extra working day for that day, an all day event is added to the top of the calendar. Clicking on that event, it's possible to delete the extra working day, maintaining inalterate the eventually appointments already added.

In the Working plan page of a provider are listed all the available extra working days.

### CODE REVIEW

**Comment by KRUAndu** [comment]
This is really useful! I'm actually using this with 1.3.1 beta1 since our employees are not with a regular schedule so to speak. 
What ended up happening was the datepicker was a bit odd. Since the update for selecting time formats (REGULAR and MILITARY), it only lets me pick in milliseconds. It also happened from the agendaWeek view, but I got it to work by changing the datepicker line in working_plan.js line 370-371:
                '<td class="extra-start editable">' + ((GlobalVariables.timeFormat === 'h:mm tt') ? '9:00 AM' : '09:00') + '</td>' +
                '<td class="extra-end editable">' + ((GlobalVariables.timeFormat === 'h:mm tt') ? '10:00 AM' : '10:00') + '</td>' + 
(maybe were these lines, maybe not, cant remember 3 weeks back 😕)
image

Could've been happening since I used an old commit.. Oops.
Anyway, my question is that how does this particular json array actually work? My knowledge in PHP/JS is not that good, but I'd want to change the way users can add (or atleast see) extra working days all together in Providers_model. Could it be done with fullCalendar's list view? https://fullcalendar.io/releases/fullcalendar/3.9.0/demos/list-views.html
How can I get the extra_working_day array in a specific form, that a separate fullCalendar could show me ALL providers extra working days? (a bit like this: https://codepen.io/kruandu/pen/VxNLBR) ?
If a client supposedly calls over the phone, the worker has to check all the providers one-by-one in the calendar, to see which providers are working that specific day. This could ease this.
Or is it just easier to maybe implement it into backend_calendar_table_view?

Loving your "extra" efforts Caine 👍

**Comment by robertzaage** [comment]
I just merged your pull request into version 1.4.0, but there is a very strange bug.

The extra working hours are only displayed for the first service per provider. All other services are are pointing to the correct dates, but there is no available slot showing up. I debugged the JSON requests happening in the background:

If service_id is 1 == correct dates with free slots are showing up
If service_id is != 1 == correct dates are showing up, but the JSON response is empty - no times selectable.

Steps to reproduce:

1. Add two services to provider
2. Add an extra day 
3. Try to book an appointment for the second service in frontend.

**Comment by robertzaage** [comment]
> I just merged your pull request into version 1.4.0, but there is a very strange bug.
> 
> The extra working hours are only displayed for the first service per provider. All other services are are pointing to the correct dates, but there is no available slot showing up. I debugged the JSON requests happening in the background:
> 
> If service_id is 1 == correct dates with free slots are showing up
> If service_id is != 1 == correct dates are showing up, but the JSON response is empty - no times selectable.
> 
> Steps to reproduce:
> 
> 1. Add two services to provider
> 2. Add an extra day
> 3. Try to book an appointment for the second service in frontend.

I guess it's a bug in src/application/controllers/Appointments.php ajax_get_available_hours function.

**Comment by KRUAndu** [comment]
> > I just merged your pull request into version 1.4.0, but there is a very strange bug.
> > The extra working hours are only displayed for the first service per provider. All other services are are pointing to the correct dates, but there is no available slot showing up. I debugged the JSON requests happening in the background:
> > If service_id is 1 == correct dates with free slots are showing up
> > If service_id is != 1 == correct dates are showing up, but the JSON response is empty - no times selectable.
> > Steps to reproduce:
> > 
> > 1. Add two services to provider
> > 2. Add an extra day
> > 3. Try to book an appointment for the second service in frontend.
> 
> I guess it's a bug in src/application/controllers/Appointments.php ajax_get_available_hours function.

Thanks for your diagnostic work :)
This might help me with upgrade to 1.4 one day.

**Comment by alextselegidis** [comment]
Merged on develop, thanks!

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Pull request merged**
