### PR TITLE
Updated German Translations 1.5.0

### PR DESCRIPTION
**Pull request by herzogmedia**
Added some missing translations and updated others for better consistency and intelligibility

### CODE REVIEW

**Comment by cn-tools** [comment]
dear @herzogmedia !

i think "$lang['wednesday_short']" should be "Mi" instead of "Mt".
See website [duden.de](https://www.duden.de/rechtschreibung/Mittwoch)

regards

**Comment by herzogmedia** [comment]
> 

> i think "$lang['wednesday_short']" should be "Mi" instead of "Mt".

It most definately should. Working in hot weather....
Thanks for pointing this out!

**Comment by cn-tools** [comment]
you havn't changed it, but it's an idea.

i think "attendants_number" should be "Maximale Teilnehmeranzahl" or similar, instead of "Begleiternummer".
I searched some time why could some people book an appointment on the same time.

**Comment by herzogmedia** [comment]
added =)

**Comment by alextselegidis** [comment]
Hello! 

Thanks for your contributions!

<small>
<table>
<tr>
<td></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Pull request merged**
