### PR TITLE
New system-wide setting to choose first weekday- Proposal for #471

### PR DESCRIPTION
**Pull request by oxteam**
Hi Alex,

Please find a proposal for you feature ticket #471.
It is based on what was developed in Easyblue + the fix I proposed to fix bug #506
(Note: Fix for #506 is also avail in a dedicated pull request - #511).

However, I did not follow Eeasyblue's label strings in the language files. This is because I think it is important to respect the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) for users. Therefore I used a similar texting as the one used in [Outlook](https://support.office.com/en-us/article/set-the-first-day-of-the-calendar-week-and-change-calendar-work-days-8f009e32-e05e-47fd-809f-7b1d82d00c3e).
Entries in the language files are in English except for French where I am able to translate.

So, calendars (backend + appointment pages) are now displayed starting with the first weekday set in the 'settings' pages.

For a better consistency, we could also imagine to sort the working plan days and break days according to the 'first day of the week' setting in the 'settings' and 'users' panels in the backend. I have not yet implemented it.

### CODE REVIEW

**Comment by alextselegidis** [comment]
Great! I'll check this out!

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by oxteam** [comment]
Hi Alex,

Here is a list of what I did to have days sorted also in the Settings and Users pages in the backend:
- Removed the `working-plan tbody` contents in `settings.php` and `users.php`
- Generating the `working-plan tbody` contents in the working plan setup function in `working_plan.js`
- Attaching the check box click event handler to the  `working-plan tbody` in order to have the event handler kept when the input check boxes are deleted when performing `$('.working-plan tbody').empty()`.
- Because the working plan setup function dynamically fills the tbody for `working-plan` and `breaks`, I perform the `.empty()` there. It allows to remove almost of calls to `.empty()` in backend_users.  These calls are still necessary only in the `resetForm` function.

- Thanks to the working-plan tbody empty calls, we have no more need to manage the checkbox and the time pickers in case of no provider selected. The whole block of the working plan table body is simply erased like already done for the break table. 

- I also corrected the sort function on dates in WorkingPlan.prototype.get.
Doing "12:00" - "14:00" returns NaN in Javascript. It is necessary to use localeCompare() instead.

- I also use this sorting function to have the newly added break inserted in chronological order when clicking on the save button.

- At last, I refresh GlobalVariables.timeFormat and GlobalVariables.firstWeekday when settings are saved. It allows to display the working plan of Business Logic tab according to the saved settings without the need to go reload the page.

**Comment by oxteam** [comment]
Hi Alex,

Please note that merging the commits of this PL in your master branch may generate a very trivial merge conflict in the French language file `translation_lang.php`. I faced it when merging these commits in my own master inherited from your master branch (after commit 3fd0c2834b4f3bca13e00f51bcbb8d0d12c73697).

The conflict resolution is then very easy:

1. Accept the following block coming from the 'first weekday' feature:

```
$lang['first_weekday'] = 'Premier jour de la semaine';
$lang['first_weekday_hint'] = 'Définit le premier jour de la semaine calendaire.';
$lang['google_analytics_code_hint'] = 'Renseignez l\'ID Google Analytics à utiliser dans la page des réservations.';
```
2. Then just replace the final **z** by a **r** for the word "Renseigne**z**" in the  the text of the `google_analytics_code_hint` language key.

So it means that 

$lang['google_analytics_code_hint'] = 'Renseigne**z** l\'ID Google Analytics à utiliser dans la page des réservations.';

becomes

$lang['google_analytics_code_hint'] = 'Renseigne**r** l\'ID Google Analytics à utiliser dans la page des réservations.';

Otherwise, if you prefer, I can also provide a new PR based on your master branch instead of you develop branch. Please let me know what is more convenient for you.

**Comment by alextselegidis** [comment]
Hello @oxteam, 

first of all thank you very much for your contributions. 

This pull request is going to land in develop and be used for the upcoming v1.4. The master branch has currently all the code for the final 1.3.2. 

I'll check this out and let you know if I have any issues. 

Cheers!

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by oxteam** [comment]
Ok, understood !

**Comment by oxteam** [comment]
FYI, I've just merged you latest commits from your develop branch (until 78362e4).

**Comment by alextselegidis** [comment]
Thanks for the help @oxteam! Great work! 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by oxteam** [comment]
FYI, I merged you latest commits from your develop branch (until 14bbd79).

**Comment by alextselegidis** [comment]
Thanks!

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Pull request merged**
