### PR TITLE
Update translations_lang.php

### PR DESCRIPTION
**Pull request by emanwebdev**

### CODE REVIEW

**Comment by alextselegidis** [comment]
Thank you very much for your contribution! I will merge your pull request tomorrow in the develop branch.

**Comment by emanwebdev** [comment]
Hi @alextselegidis 
ok, 
btw
i'd like to install & test the current version; aka the very last version

how to download to test the VERY last version of the code?

**Comment by alextselegidis** [comment]
Version 1.1 is the latest version. Download this file:

https://github.com/alextselegidis/easyappointments/releases/download/1.1.0/easyappointments_1.1.0.zip

**Comment by alextselegidis** [comment]
Merged! https://github.com/alextselegidis/easyappointments/commit/f3de3746da973573c7cd82f2fb954c1f9f35e03c 

Thanks :)

**Pull request closed without merging**
