### PR TITLE
Move Dockerfile and fix conflict with library with security-advisories  ￼

### PR DESCRIPTION
**Pull request by defro**
Thanks to share your project @alextselegidis  !

I move Dockerfile to root folder in order to deploy project in the cloud and I create a volume for mysql data.

Regards,
Joël

### CODE REVIEW

**Comment by DonSYS91** [comment]
Thank you @defro for this PR, I was in fact trying myself to find a way to build vendor directory within a multistage docker build instead of doing it on host but there's a fundamental problem here.
When you copied the files at the final stage from the composer stage:
`# Copy vendor from composer stage
COPY --from=composer /var/www/html/vendor    /var/www/html/vendor`

And then you ran docker with the entire volume mounted:
`volumes:
            - ../:/var/www/html`

Here you basically just hid the entire vendor directory because the volume will copy back the entire host folder (without vendor) back to the container and thus vendor will remain hidden.

There are some approaches around that but none of them are reliable and therefore I decided to revert back to build composer on host.
I'm wondering if you really got that to work during your tests.

**Comment by defro** [comment]
Many thanks @DonSYS91 for your review.
Yes it's impossible to combine docker-compose volume with docker build to have vendor folder. 

The purpose of my PR is to deploy this project without need to build vendor directory on host machine. So it means I can create a docker image containing the vendor folder.

Regards,
Joël

(sorry for my bad english)

**Comment by DonSYS91** [comment]
I know exactly what are you trying to achieve but that's also not possible.
When the container starts with the volume mounting of the entire root dir, the mounting will write back to the container and remove the vendor folder.
Are you really sure that the vendor dir presents in the container?

Btw your english is perfect.

**Comment by defro** [comment]
Hello @DonSYS91 

I made some changes in Dockerfile to optimize layer and copy php ini override file, also fix rights to `storage` folder.

Actually you can test the application without docker-compose, you need to launch container by this command (you must be in the root folder):
```bash
docker build . -t easyappointments && docker run --name easyappointments -p 80:80 easyappointments
```

Of course, you need a running mysql server ready...

I let you test this and tell me what you think about it.

Regards

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this PR!

Couple of questions: 

Since docker-compose.yml references the Docker file with a relative path, why would this need to be at the root? 

Also there used to be a volume for the MySQL data any way, so could you explain why the new volume is needed? 

<small>
<table>
<tr>
<td></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by defro** [comment]
Hello @alextselegidis 

Thanks for your interest for my PR.

1. Dockerfile should be at the root folder because `COPY` instruction only work for current and children folders; so this instruction cannot access to parent folder.
2. I can rollback creation of this volume if you prefer. I created this "new" volume to avoid right issues on mysql files. During my tests I cannot erase database files without change rights (chmod) on files, so by creating a docker volume you can easily remove volume with this command `docker volume rm <volume_name>`

Regards

**Comment by alextselegidis** [comment]
Hi @defro, 

I just updated the project's docker configuration, based on your changes, feedback and some other resources I found online.

Feel free to check (develop) that and open a new ticket if you find anything that does not work. 

<small>
<table>
<tr>
<td></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Pull request closed without merging**
