### PR TITLE
Added Filter to Appointments API

### PR DESCRIPTION
**Pull request by daddyfix**
This is the first time I use Github to FORK a project. Please let me know if I have followed proper etiquette.

I added the FILTER request for the API for Appointments. It works like this
**your-easyappointments/index.php//api/v1/appointments/filter/TABLE NAME/SEARCH STRING**

NOTE: This filter uses the **LIKE** command in MySQL

```
$ curl --user someone:password "http://your-easyappointments/index.php/api/v1/appointments/filter/start_datetime/13:00"
{
    "id": 66,
    "book": "2017-02-07 20:22:19",
    "start": "2017-02-08 13:00:00",
    "end": "2017-02-08 13:30:00",
    "hash": "28f50c4825c080f301711b6b1a97643b",
    "notes": "My dog needs glasses",
    "customerId": 86,
    "providerId": 85,
    "serviceId": 13,
    "googleCalendarId": null
}
```
or like this
```
curl --user someone:password "http://your-easyappointments/index.php/api/v1/appointments/filter/notes/DOG"
{
    "id": 66,
    "book": "2017-02-07 20:22:19",
    "start": "2017-02-08 13:00:00",
    "end": "2017-02-08 13:30:00",
    "hash": "28f50c4825c080f301711b6b1a97643b",
    "notes": "My dog needs glasses",
    "customerId": 86,
    "providerId": 85,
    "serviceId": 13,
    "googleCalendarId": null
}
```

### CODE REVIEW

**Comment by alextselegidis** [comment]
Hi there! Thank you very much for your pull request. I have some notes though: 

1. E!A's API follows strict REST architecture which makes it a bit hard to accept a URL like this: 

`/api/v1/appointments/filter/start_datetime/13:00`

Instead I would like this to work with a GET parameter: 

`/api/v1/appointments?start_datetime=13:00`


2. Work with the response object in order to keep things re-usable: 

Being said I would like to see a new `filter` method in the response ...

```
$response->encode($this->parser)
                     ->search()
                     ->filter(['start_datetime']) // Data will be filtered with the value of $_GET['start_datetime']
                     ->sort()
                     ->paginate()
                     ->minimize()
                     ->singleEntry($value)
+                    ->output();
```

Cheers 

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by daddyfix** [comment]
Alex,

It snowing very hard here, about 12cm of snow so far.
I worked on the filter today and managed to get it working very well.
I updated 3 files
 - engine/Api/V1/Processors/Filter.php
 - engine/Api/V1/Response.php
 - application/controllers/api/v1/Appointments.php

I need some help updating my fork or you master on Github??... I am totally
confused on how to do this

Here are the steps I took (which I know now are wrong)

1. Copied my full working path to a temp location ~/easyappointments on my
server so I don't mess up the working code
2. Moved to the working temp dir with cd ~/easyappointments
2. Ran '$ git fetch upstream' - nothing happened
3. Ran '$ git merge upstream/master'

Got this error. Now I don't know how to fix it
Updating 2010418..986c8dc
error: Your local changes to the following files would be overwritten by
merge:
    src/application/controllers/api/v1/API_V1_Controller.php
    src/application/controllers/api/v1/Appointments.php
Please, commit your changes or stash them before you can merge.
Aborting

4. Tried a million things and I can't figure out how to get this to work.
I'm really new at this...

Please help.

Should I update my Fork of easyAppointments or you master?
How do I push the updates for a pull request compare?

**Comment by alextselegidis** [comment]
Hi! You will have first to commit your changes and then updated your fork :)

```
error: Your local changes to the following files would be overwritten by
merge:
    src/application/controllers/api/v1/API_V1_Controller.php
    src/application/controllers/api/v1/Appointments.php
Please, commit your changes or stash them before you can merge.
Aborting
```

<small>
<table>
<tr>
<td></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by daddyfix** [comment]
Please forgive me but it actually took more brain power to learn how to GITHUB than it took to program the php class Filter.php!

As you can see in the Filter.php.... This is how it works
Lets say there are two records...

**Records**
```
[
    {
        "id": 65,
        "book": "2017-02-07 20:21:25",
        "start": "2017-02-09 09:00:00",
        "end": "2017-02-09 12:30:00",
        "hash": null,
        "notes": "Dr. Apptmnt",
        "customerId": null,
        "providerId": 85,
        "serviceId": null,
        "googleCalendarId": null
    },
    {
        "id": 66,
        "book": "2017-02-07 20:22:19",
        "start": "2017-02-08 13:00:00",
        "end": "2017-02-08 13:30:00",
        "hash": "28f50c4825c080f301711b6b1a97643b",
        "notes": "My Dog needs glasses",
        "customerId": 86,
        "providerId": 85,
        "serviceId": 13,
        "googleCalendarId": null
    }
]
```
**This is how the search works.**
 - GET key is the table column name.
   _the table columns are trimmed before any underscores. So start_datetime column is referred to as start and end_dattetime is just end._
 - GET value is the search string (urlencoded)
   _the value is urldecoded and converted to lower case for searching_

**API GET Call**
```
$ curl -u username:password "https://somewhere.com/index.php/api/v1/appointments?notes=Dog+needs+GLASS"
[
    {
        "id": 66,
        "book": "2017-02-07 20:22:19",
        "start": "2017-02-08 13:00:00",
        "end": "2017-02-08 13:30:00",
        "hash": "28f50c4825c080f301711b6b1a97643b",
        "notes": "My Dog needs glasses",
        "customerId": 86,
        "providerId": 85,
        "serviceId": 13,
        "googleCalendarId": null
    }
]
```

**Comment by matzrm** [comment]
Hi,

this code not works for some fields of the table.
For example if the field is _id_users_customer_, the code cut it into _id_ and the filter not works properly.

I think that it is easier to filter through the encoded name.

**Pull request closed without merging**
