### PR TITLE
Made it possible to change default language in main config file

### PR DESCRIPTION
**Pull request by icecoldfire**
It is now possible to change the default language in the main config file. So that other user can change this quick without the need to search the other config files.

### CODE REVIEW

**Comment by alextselegidis** [comment]
Hey that's a nice one. Thanks ;)

**Comment by alextselegidis** [comment]
I will merge your pull request to the release branch and correct the string thing. Thank you very much for the contribution :)

**Comment by alextselegidis** [comment]
Done!
https://github.com/alextselegidis/easyappointments/commit/728c740173de27c812343a20f854924cae1e7ae6

**Comment by icecoldfire** [comment]
Indeed, I forget to copy the ' '.

**Pull request closed without merging**
