### PR TITLE
Update Caldav_sync.php for correct URI parsing

### PR DESCRIPTION
**Pull request by sandro-byte32**
Issue:
[Successful Caldav Login but no Syncing](https://github.com/alextselegidis/easyappointments/issues/1574#top)
#1574

should be resolved with this

### CODE REVIEW

**Comment by alextselegidis** [comment]
Hello! 

Thanks for submitting this. 

I will give it a try. 

<small>
<table>
<tr>
<td></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
FYI this PR was tested by community members and indeed fixes issues with Nextcloud and other CalDAV servers 

<small>
<table>
<tr>
<td></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by sandro-byte32** [comment]
Thank you for letting me know. I'm glad I can contribute to this awesome project!

**Comment by alextselegidis** [comment]
Hello! 

Thanks for this PR.

I had to manually merge it, but it works like a charm. 

<small>
<table>
<tr>
<td></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by quentinreytinas** [comment]
Hello,
I have the same issue with the docker image... Do you think you can update the docker version please?
Thanks!

**Comment by alextselegidis** [comment]
Yes, it will be updated as soon as the next maintenance update is released. 

<small>
<table>
<tr>
<td></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by quentinreytinas** [comment]
I manually modified the file, and it works perfectly. Thank you.

**Pull request closed without merging**
